# -*- coding: utf-8 -*-
"""ResumeMatcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WgZ8wV4cIex1se72fUDcJ4qKh9tEtLf4
"""



class JobDescription:
    def __init__(self, title, required_skills, required_experience_years, required_qualification):
        self.title = title
        self.required_skills = required_skills
        self.required_experience_years = required_experience_years
        self.required_qualification = required_qualification

class Resume:
    def __init__(self, candidate_name, skills, experience_years, qualification):
        self.candidate_name = candidate_name
        self.skills = skills
        self.experience_years = experience_years
        self.qualification = qualification

def match_skills(resume, job_description):
    """
    Compares skills from a resume with required skills from a job description.

    Args:
        resume (Resume): The candidate's resume object.
        job_description (JobDescription): The job description object.

    Returns:
        float: The skill match score between 0 and 1.
    """
    resume_skills = set(skill.lower() for skill in resume.skills)
    required_skills = set(skill.lower() for skill in job_description.required_skills)

    common_skills = len(resume_skills.intersection(required_skills))

    if not required_skills:
        # If no skills are required, consider it a perfect match if the resume has any skills, or 1.0
        return 1.0

    score = common_skills / len(required_skills)
    return score

def match_experience(resume, job_description):
    """
    Compares the candidate's experience with the required experience for the job.

    Args:
        resume (Resume): The candidate's resume object.
        job_description (JobDescription): The job description object.

    Returns:
        float: The experience match score between 0 and 1.
    """
    required_exp = job_description.required_experience_years
    candidate_exp = resume.experience_years

    if required_exp == 0:
        return 1.0
    elif candidate_exp >= required_exp:
        return 1.0
    else:
        return candidate_exp / required_exp

def match_qualification(resume, job_description):
    """
    Compares the candidate's highest qualification with the required qualification for the job.

    Args:
        resume (Resume): The candidate's resume object.
        job_description (JobDescription): The job description object.

    Returns:
        float: The qualification match score between 0 and 1.
    """
    qualification_levels = {
        "none": 0,
        "high school": 1,
        "associate's degree": 2,
        "bachelor's degree": 3,
        "master's degree": 4,
        "phd": 5
    }

    candidate_qual = resume.qualification.lower() if resume.qualification else "none"
    required_qual = job_description.required_qualification.lower() if job_description.required_qualification else "none"

    candidate_level = qualification_levels.get(candidate_qual, 0)
    required_level = qualification_levels.get(required_qual, 0)

    # If required qualification is not in mapping or very basic and candidate has any qual, return 1.0
    if (required_level == 0 or required_qual in ["none", "high school"]) and candidate_level > 0:
        return 1.0

    if required_level == 0 and candidate_level == 0:
        return 1.0 # Both have no specific qualification, consider it a match

    if candidate_level >= required_level:
        return 1.0
    elif required_level > 0: # Ensure no division by zero
        return candidate_level / required_level
    else:
        return 0.0 # Should not be reached if conditions above are correct, but as a fallback

def calculate_overall_score(resume, job_description):
    """
    Calculates the overall match score between a resume and a job description.

    Args:
        resume (Resume): The candidate's resume object.
        job_description (JobDescription): The job description object.

    Returns:
        float: The overall match score between 0 and 1.
    """
    # Define weights for each matching category
    # These weights can be adjusted based on importance
    skill_weight = 0.5
    experience_weight = 0.3
    qualification_weight = 0.2

    # Ensure weights sum up to 1 for normalization
    total_weight = skill_weight + experience_weight + qualification_weight
    if total_weight != 1.0:
        skill_weight /= total_weight
        experience_weight /= total_weight
        qualification_weight /= total_weight

    # Get individual match scores
    skill_score = match_skills(resume, job_description)
    experience_score = match_experience(resume, job_description)
    qualification_score = match_qualification(resume, job_description)

    # Calculate the weighted overall score
    overall_score = (
        skill_score * skill_weight +
        experience_score * experience_weight +
        qualification_score * qualification_weight
    )

    return overall_score

# Example Usage (You can uncomment and run this section to test)
# Define a job description
job1 = JobDescription(
    title="Software Engineer",
    required_skills=["Python", "Java", "SQL", "Django"],
    required_experience_years=3,
    required_qualification="bachelor's degree"
)

# Define some resumes
resume1 = Resume(
    candidate_name="Alice Smith",
    skills=["Python", "SQL", "C++", "Django"],
    experience_years=4,
    qualification="master's degree"
)

resume2 = Resume(
    candidate_name="Bob Johnson",
    skills=["Java", "C#"],
    experience_years=2,
    qualification="bachelor's degree"
)

resume3 = Resume(
    candidate_name="Charlie Brown",
    skills=["Python", "SQL"],
    experience_years=1,
    qualification="high school"
)

# Calculate and print scores
print(f"\nMatching {resume1.candidate_name} to {job1.title}:")
print(f"Skill Score: {match_skills(resume1, job1):.2f}")
print(f"Experience Score: {match_experience(resume1, job1):.2f}")
print(f"Qualification Score: {match_qualification(resume1, job1):.2f}")
overall_score1 = calculate_overall_score(resume1, job1)
print(f"Overall Match Score: {overall_score1:.2f} ({(overall_score1 * 100):.0f}%)\n")

print(f"Matching {resume2.candidate_name} to {job1.title}:")
print(f"Skill Score: {match_skills(resume2, job1):.2f}")
print(f"Experience Score: {match_experience(resume2, job1):.2f}")
print(f"Qualification Score: {match_qualification(resume2, job1):.2f}")
overall_score2 = calculate_overall_score(resume2, job1)
print(f"Overall Match Score: {overall_score2:.2f} ({(overall_score2 * 100):.0f}%)\n")

print(f"Matching {resume3.candidate_name} to {job1.title}:")
print(f"Skill Score: {match_skills(resume3, job1):.2f}")
print(f"Experience Score: {match_experience(resume3, job1):.2f}")
print(f"Qualification Score: {match_qualification(resume3, job1):.2f}")
overall_score3 = calculate_overall_score(resume3, job1)
print(f"Overall Match Score: {overall_score3:.2f} ({(overall_score3 * 100):.0f}%)\n")